# This is a basic workflow to help you get started with Actions

name: Deploy de site html para uma instancia EC2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #  branches: [ "main" ]
  pull_request:
    branches: [ "main", "prod", "stag" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  copy-html-ec2:
    environment: Development
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a set of commands using the runners shell
      - name: Run a SSH command remotely
        run: |
          ls
          echo "${{ secrets.SSH_SECRET_KEY }}" > moongy-key.pem
          chmod 400 moongy-key.pem 
          scp -o StrictHostKeyChecking=no -i moongy-key.pem -r ./assets ubuntu@ec2-44-223-24-163.compute-1.amazonaws.com:/var/www/html/ea/assets/
          scp -o StrictHostKeyChecking=no -i moongy-key.pem *.html *.css *.png *.js ubuntu@ec2-44-223-24-163.compute-1.amazonaws.com:/var/www/html/ea/
